import type { Ref, Timestamped, WithId } from './common';
import type {
  AttendanceStatus,
  EnrollmentStatus,
  Gender,
  GuardianRelationship,
  HousingType,
  LessonPlanStatus,
  LocationType,
  MaritalStatus,
  ConsentStatus,
  SemesterStatus,
  StudentOrganization,
  StudentStatus,
  SubjectType,
  TeacherStatus,
  UserStatus,
  Vaccine,
  VaccinationCampaignStatus,
  VaccinationStatus,
  PersonType,
} from './enums';

/**
 * Response shapes for the modules the admin panel reads.
 *
 * The API declares request DTOs in its OpenAPI document (see
 * `src/types/api-schema.d.ts`, regenerated by `npm run gen:api`) but returns
 * serialized Mongoose documents, which the document does not describe. These
 * interfaces mirror `src/database/schemas/*.schema.ts` in the API, with two
 * transforms the serializer applies on the way out:
 *
 *   • `_id` is rendered as `id`
 *   • `Date` becomes an ISO 8601 string
 *
 * Reference fields are `Ref<T>`: an id string on list endpoints, a populated
 * object on detail endpoints. Read them with `refId()` / `refObject()`.
 */

interface BaseDocument extends WithId, Timestamped {
  deletedAt?: string | null;
}

// ── Locations ───────────────────────────────────────────────────────────────

export interface Location extends BaseDocument {
  nameLo: string;
  nameEn?: string | null;
  code?: string | null;
  type: LocationType;
  parentId?: Ref<Location>;
  /** Province → district chain, root first. */
  ancestors: string[];
  depth: number;
}

/** `GET /locations/tree` — the whole hierarchy, nested and cached server-side. */
export interface LocationTreeNode extends Location {
  children?: LocationTreeNode[];
}

// ── Academic structure ──────────────────────────────────────────────────────

export interface SchoolYear extends BaseDocument {
  code: string;
  nameLo: string;
  nameEn?: string | null;
  startDate: string;
  endDate: string;
  isActive: boolean;
}

export interface Semester extends BaseDocument {
  schoolYearId: Ref<SchoolYear>;
  number: number;
  nameLo: string;
  nameEn?: string | null;
  startDate: string;
  endDate: string;
  status: SemesterStatus;
  isActive: boolean;
}

export interface GradeLevel extends BaseDocument {
  code: string;
  nameLo: string;
  nameEn?: string | null;
  level: number;
  isExitLevel: boolean;
}

export interface Classroom extends BaseDocument {
  schoolYearId: Ref<SchoolYear>;
  gradeLevelId: Ref<GradeLevel>;
  name: string;
  homeroomTeacherId?: Ref<Teacher>;
  capacity: number;
  /** Maintained by the API as students are enrolled or moved. */
  currentCount: number;
  room?: string | null;
  isActive: boolean;
}

/**
 * A `ສາຍວິຊາ` — the department both a subject and a teacher belong to.
 *
 * It is what makes maths one department rather than seven rows: `Subject` is per
 * grade level, this is not. The lesson-plan compliance matrix groups by it, and
 * a submission notifies this group's head rather than every head in the school.
 */
export interface SubjectGroup extends BaseDocument {
  code: string;
  nameLo: string;
  nameEn?: string | null;
  /** Reviews this group's lesson plans; `null` while the post is vacant. */
  headTeacherId?: Ref<Teacher>;
  sortOrder: number;
  isActive: boolean;
}

export interface Subject extends BaseDocument {
  code: string;
  nameLo: string;
  nameEn?: string | null;
  gradeLevelId: Ref<GradeLevel>;
  /** `null` for a subject not yet filed under a department. */
  subjectGroupId?: Ref<SubjectGroup>;
  type: SubjectType;
  credits: number;
  hoursPerWeek: number;
  passingPercentage?: number | null;
  /**
   * The strands the monthly mark sheet splits this subject into — ຟີຊິກ / ເຄມີ /
   * ຊີວະ inside ວິທະຍາສາດທຳມະຊາດ. Empty for a subject marked as a whole.
   */
  strands?: string[];
  isActive: boolean;
}

// ── People ──────────────────────────────────────────────────────────────────

/** Birthplace, as the three administrative levels — plain names, not locations. */
export interface PlaceOfBirth {
  village?: string | null;
  district?: string | null;
  province?: string | null;
}

export interface TeacherEducation {
  institution?: string | null;
  /** The academic year completed, written `2016-2017`. */
  graduatedYear?: string | null;
}

/** A teacher's parent as recorded on the staff form — not a `Guardian`. */
export interface TeacherParent {
  fullNameLo?: string | null;
  address?: string | null;
  occupation?: string | null;
}

export interface Teacher extends BaseDocument {
  teacherCode: string;
  /** Honorific as written — `ນ.`, `ທ.`. Kept out of the given name. */
  title?: string | null;
  firstNameLo: string;
  lastNameLo: string;
  firstNameEn?: string | null;
  lastNameEn?: string | null;
  gender: Gender;
  dateOfBirth?: string | null;
  ethnicity?: string | null;
  placeOfBirth?: PlaceOfBirth | null;
  nationalId?: string | null;
  phone?: string | null;
  email?: string | null;
  villageId?: Ref<Location>;
  addressDetail?: string | null;
  photoKey?: string | null;
  /** Signed URL, minted on both the list and the detail read. Expires in 15 min. */
  photoUrl?: string | null;
  qualification?: string | null;
  specialization?: string | null;
  education?: TeacherEducation | null;
  /** What they teach, by name. The timetable's hard link is `TeachingAssignment`. */
  teachingSubjects?: string[];
  professionalLevel?: string | null;
  hireDate?: string | null;
  /** Entry into public service, which predates being hired here. */
  joinedOrgDate?: string | null;
  maritalStatus?: MaritalStatus | null;
  childrenCount?: number | null;
  housingType?: HousingType | null;
  livingWith?: string | null;
  siblings?: string | null;
  father?: TeacherParent | null;
  mother?: TeacherParent | null;
  status: TeacherStatus;
  isAcademicHead: boolean;
  /** The department they are on the roster of — not the one they head. */
  subjectGroupId?: Ref<SubjectGroup>;
}

export interface Guardian extends BaseDocument {
  firstNameLo: string;
  lastNameLo: string;
  gender?: Gender | null;
  dateOfBirth?: string | null;
  nationalId?: string | null;
  phone: string;
  alternatePhone?: string | null;
  email?: string | null;
  occupation?: string | null;
  workplace?: string | null;
  villageId?: Ref<Location>;
  addressDetail?: string | null;
}

/**
 * A guardian as embedded on a student.
 *
 * Name and phone are denormalized copies, so a roster or an emergency-contact
 * list needs no join.
 */
export interface StudentGuardianLink {
  guardianId: Ref<Guardian>;
  fullNameLo: string;
  phone: string;
  relationship: GuardianRelationship;
  isPrimary: boolean;
  isEmergencyContact: boolean;
  canViewRecords: boolean;
}

/**
 * Where a student currently sits, as the students list returns it.
 *
 * Placement lives in the `enrollments` collection, not on the student — the API
 * resolves the active enrollment for the requested (or active) school year and
 * attaches it to each row, so a roster column costs no extra request.
 */
export interface StudentPlacement {
  enrollmentId: string;
  classroomId: string;
  classroomName: string;
  gradeLevelId: string;
  gradeLevelCode: string | null;
  schoolYearId: string;
  rollNumber: number | null;
  enrolledAt: string;
}

/** `ເຍົາວະຊົນ` / `ເຂົ້າຊາວໜຸ່ມ` / `ເຂົ້າແມ່ຍິງ` — the fact and `ວັນເຂົ້າ`. */
export interface StudentOrganizationMembership {
  organization: StudentOrganization;
  joinedDate: string;
}

export interface Student extends BaseDocument {
  studentCode: string;
  /**
   * `ນາງ` or `ທ້າວ`, derived server-side from `gender` — read-only.
   *
   * Absent when the record's gender is not yet on file, which is the whole
   * reason it is not a stored field: a honorific and a gender that disagree
   * were the register's typing, not two facts.
   */
  title?: string | null;
  firstNameLo: string;
  lastNameLo: string;
  firstNameEn?: string | null;
  lastNameEn?: string | null;
  nickname?: string | null;
  nicknameEn?: string | null;
  gender: Gender;
  dateOfBirth: string;
  placeOfBirth?: string | null;
  nationality?: string | null;
  ethnicity?: string | null;
  nationalId?: string | null;
  phone?: string | null;
  /** The number the office rings about this child — often not the student's own. */
  contactPhone?: string | null;
  /** Who `contactPhone` reaches, when that is not a guardian on file. */
  contactName?: string | null;
  villageId?: Ref<Location>;
  addressDetail?: string | null;
  photoKey?: string | null;
  photoUrl?: string | null;
  guardians: StudentGuardianLink[];
  organizations: StudentOrganizationMembership[];
  admissionDate?: string | null;
  status: StudentStatus;
  notes?: string | null;
  /** Present on list responses. `null` means the student has no class yet. */
  currentEnrollment?: StudentPlacement | null;
}

/**
 * Another student who shares a guardian with the one being viewed.
 *
 * The school stores no sibling link — a family is the guardian both children
 * point at — so `sharedGuardians` is what makes the connection explainable
 * rather than asserted.
 */
export interface Sibling extends Student {
  sharedGuardians: {
    guardianId: string;
    fullNameLo: string;
    relationship: GuardianRelationship;
  }[];
}

// ── Enrollment ──────────────────────────────────────────────────────────────

/**
 * A student's placement in one classroom for one school year.
 *
 * `studentCode` and `studentNameLo` are denormalized copies, so a class roster
 * renders without a join. Reference fields are populated on the per-student
 * history endpoint and left as ids on the roster.
 */
export interface Enrollment extends BaseDocument {
  studentId: Ref<Student>;
  studentCode: string;
  studentNameLo: string;
  classroomId: Ref<Classroom>;
  schoolYearId: Ref<SchoolYear>;
  gradeLevelId: Ref<GradeLevel>;
  enrolledAt: string;
  status: EnrollmentStatus;
  rollNumber?: number | null;
  statusChangedAt?: string | null;
  statusReason?: string | null;
  transferredToClassroomId?: Ref<Classroom>;
}

// ── Attendance ──────────────────────────────────────────────────────────────

/**
 * One student's presence on one day, or in one period of it.
 *
 * `period` is `0` for whole-day roll call and `1..n` for a per-period one; it is
 * part of the API's uniqueness key, so a school may use either model or both.
 * The list endpoint populates student, classroom and subject; the roll-call
 * sheet and the summaries return their own flattened shapes instead.
 */
export interface Attendance extends BaseDocument {
  studentId: Ref<Student>;
  /** The timetabled lesson this roll call belongs to. */
  teachingAssignmentId: Ref<TeachingAssignment>;
  classroomId: Ref<Classroom>;
  semesterId: Ref<Semester>;
  schoolYearId: Ref<SchoolYear>;
  date: string;
  period: number;
  subjectId: Ref<Subject>;
  /** The teacher whose lesson it was, per the timetable. */
  teacherId: Ref<Teacher>;
  status: AttendanceStatus;
  /** Only meaningful when `status` is `late`. */
  minutesLate?: number | null;
  reason?: string | null;
  /** Whoever submitted it, which is not always `teacherId`. */
  recordedBy: Ref<User>;
}

// ── Behavior log ────────────────────────────────────────────────────────────

/**
 * One student's line in the homeroom behaviour register.
 *
 * The paper form's row mixes two levels — a note about the class, and named
 * students with what each did — and is stored one record per student so a
 * student's own history is a direct lookup. `groupId` is what puts a row back
 * together: several records written in one entry share it, and it is the id the
 * write endpoints take.
 *
 * `studentId` is null on a row that only records the state of the class, which
 * the paper form allows and homeroom teachers use constantly.
 */
export interface BehaviorLog extends BaseDocument {
  groupId: string;
  studentId?: Ref<Student> | null;
  /** The timetabled lesson the observation was made in. */
  teachingAssignmentId: Ref<TeachingAssignment>;
  classroomId: Ref<Classroom>;
  semesterId: Ref<Semester>;
  schoolYearId: Ref<SchoolYear>;
  date: string;
  period: number;
  subjectId: Ref<Subject>;
  /** The teacher whose lesson it was, per the timetable. */
  teacherId: Ref<Teacher>;
  /** ສະພາບລວມພາຍໃນຫ້ອງ — the class as a whole. */
  classNote?: string | null;
  /** ພຶດຕິກຳ(ລາຍບຸກຄົນ) — what this student did. */
  behavior?: string | null;
  /** ຕັດຄະແນນ/ຕັກເຕືອນ — free text, as written on the paper form. */
  action?: string | null;
  remark?: string | null;
  /** Whoever filed it, which is not always `teacherId`. */
  recordedBy: Ref<User>;
}

// ── Teaching assignments ────────────────────────────────────────────────────

/**
 * One weekly period.
 *
 * Times are local wall-clock `"HH:mm"` with no date or timezone part, so they
 * compare lexicographically in chronological order — which is what both the
 * API's overlap check and the timetable sorting rely on.
 */
export interface SchedulePeriod {
  /** 0 = Sunday … 6 = Saturday, matching `Date#getDay()`. */
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  /** Physical room. When set, the API also checks it for double-booking. */
  room?: string | null;
  periodNumber?: number | null;
  /**
   * A slot two teachers take turns in.
   *
   * The school runs some periods as a swap — one teacher takes ມ.2/ກ while the
   * other takes ມ.2/ຂ, then they trade — so every arrangement is stored and the
   * slot legitimately holds more than one lesson. Marked periods are exempt from
   * the API's clash check against each other, and only against each other.
   */
  isRotating?: boolean;
}

/**
 * Who teaches which subject, to which class, in which semester.
 *
 * The list endpoint populates teacher, subject and classroom; the two timetable
 * endpoints populate only the two references the other axis does not already
 * fix (a teacher's timetable carries subject and classroom, and vice versa).
 */
export interface TeachingAssignment extends BaseDocument {
  teacherId: Ref<Teacher>;
  subjectId: Ref<Subject>;
  classroomId: Ref<Classroom>;
  semesterId: Ref<Semester>;
  schoolYearId: Ref<SchoolYear>;
  schedule: SchedulePeriod[];
  isActive: boolean;
  notes?: string | null;
}

// ── Lesson plans ────────────────────────────────────────────────────────────

/** One taught session inside a week's plan. */
export interface LessonActivity {
  /** Present on stored activities; absent on ones being composed in the form. */
  id?: string;
  topic: string;
  date: string;
  durationMinutes?: number | null;
  objectives?: string | null;
  materials: string[];
  teachingMethod?: string | null;
  /** Set after the lesson actually happened. */
  isCompleted: boolean;
  reflection?: string | null;
}

/** One approve/return decision; the array is the full review history. */
export interface LessonPlanReview {
  id?: string;
  reviewerId: string;
  reviewerName: string;
  decision: 'approved' | 'returned';
  comment?: string | null;
  reviewedAt: string;
}

export interface LessonPlanAttachment {
  key: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  uploadedAt: string;
}

/**
 * A week's plan for one lesson.
 *
 * `weekStartDate`, `weekEndDate` and `dueDate` are all derived by the API —
 * the week is snapped to its Monday and the deadline comes from school policy,
 * so none of the three is ever sent by the client. That is what makes `isLate`
 * mean something and what lets the compliance matrix match a plan to a cell by
 * exact date.
 */
export interface LessonPlan extends BaseDocument {
  teacherId: Ref<Teacher>;
  subjectId: Ref<Subject>;
  classroomId: Ref<Classroom>;
  semesterId: Ref<Semester>;
  title: string;
  description?: string | null;
  weekStartDate: string;
  weekEndDate: string;
  activities: LessonActivity[];
  attachments: LessonPlanAttachment[];
  status: LessonPlanStatus;
  dueDate: string;
  submittedAt?: string | null;
  /** Fixed at submission — a later policy change cannot rewrite it. */
  isLate: boolean;
  reviews: LessonPlanReview[];
  lastReviewedAt?: string | null;
}

// ── Accounts ────────────────────────────────────────────────────────────────

export interface Role extends BaseDocument {
  code: string;
  nameLo: string;
  nameEn: string;
  description?: string | null;
  permissions: { resource: string; actions: string[] }[];
  /** System roles cannot be deleted. */
  isSystem: boolean;
}

export interface User extends BaseDocument {
  username: string;
  email?: string | null;
  roleId: Ref<Role>;
  personType: PersonType;
  personId?: string | null;
  status: UserStatus;
  lastLoginAt?: string | null;
  lockedUntil?: string | null;
  mustChangePassword: boolean;
  locale: string;
}

// ── Communication (read-only surfaces used by the dashboard) ─────────────────

export interface Announcement extends BaseDocument {
  titleLo: string;
  titleEn?: string | null;
  bodyLo?: string;
  priority: string;
  publishedAt?: string | null;
  isPublished?: boolean;
}

export interface CalendarEvent extends BaseDocument {
  titleLo: string;
  titleEn?: string | null;
  type: string;
  startDate: string;
  endDate?: string | null;
  isAllDay?: boolean;
}

// ── Health ──────────────────────────────────────────────────────────────────

/**
 * Who a vaccination round is *offered* to — the filter behind the student picker.
 *
 * Not the roll: that is the campaign's explicit `studentIds`. This is still the
 * only place a round is girls-only, and it is a decision someone recorded about
 * the campaign, never something derived from a student's gender — the dose count
 * of a girls-only round and the female student count are two different figures.
 */
export interface CampaignEligibility {
  /** `null` covers every student. */
  gender?: Gender | null;
  /** Empty covers every grade. */
  gradeLevelIds: Ref<GradeLevel>[];
  bornFrom?: string | null;
  bornTo?: string | null;
}

export interface VaccinationCampaign extends BaseDocument {
  nameLo: string;
  vaccine: Vaccine;
  doseNumber: number;
  scheduledDate: string;
  schoolYearId: Ref<SchoolYear>;
  eligibility: CampaignEligibility;
  /**
   * The students the round covers, picked one by one.
   *
   * Explicit rather than swept from `eligibility`, so no child lands on a dose
   * sheet nobody chose. The cost is a list someone maintains: a newcomer is not
   * on the round until the office adds them.
   */
  studentIds: string[];
  provider?: string | null;
  status: VaccinationCampaignStatus;
  notes?: string | null;
}

/** `ໃບຍິນຍອມ` from a guardian on the student's own list. */
export interface VaccinationConsent {
  status: ConsentStatus;
  guardianId?: Ref<Guardian> | null;
  decidedAt?: string | null;
  method?: string | null;
}

/** One student, one vaccine, one dose. */
export interface Vaccination extends BaseDocument {
  studentId: Ref<Student>;
  /** `null` for a dose given at a clinic rather than in a school round. */
  campaignId?: Ref<VaccinationCampaign> | null;
  vaccine: Vaccine;
  doseNumber: number;
  status: VaccinationStatus;
  administeredDate?: string | null;
  batchNumber?: string | null;
  provider?: string | null;
  consent: VaccinationConsent;
  notes?: string | null;
}
